# ==========================================
# LITH Server Configuration File (v1.0.4)
# ==========================================

# Port d'écoute du serveur réseau
PORT=8090

# Répertoire contenant les fichiers statiques web à servir
PUBLIC_DIR=public